spring:
  application:
    name: RealTimeCommunicationService
  cloud:
    nacos:
      discovery:
        server-addr: 14.103.140.112:18375
  redis:
    database: 0
    host: 14.103.140.112
    port: 59000
    password: e65K4t8w2

server:
  port: 8083
netty:
  name: NettyService
  port: 9000