spring:
  application:
    name: RealTimeCommunicationService
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.15.45:18375
  redis:
    database: 0
    host: 120.26.15.45
    port: 59000
    password: e65K4t8w2

server:
  port: 8083
netty:
  port: 9000